### PR TITLE
K2

### PR DESCRIPTION
**Pull request by jassal**
Fix for WF-1589

Show warming message to user when he click the Delete button without selecting any task.

### CODE REVIEW

**Comment by veresh** [comment]
I am not sure why this issue requires so many file changes

**Comment by jassal** [comment]
Because this pull request include 6 commits. I think that's the reason it
shows many file changes.

**Comment by veresh** [comment]
which other issue is resolved with these commits

**Comment by jassal** [comment]
This pull request include fix for WF-1589, WF-1582, WF-1581, WF-1583 and
one warning message fix in ui-fw.

**Comment by veresh** [comment]
Please update the commit so that it has all this information and why are we
putting so many fixes in one commit.

On Sun, Feb 3, 2013 at 7:01 PM, Ravinderjit notifications@github.comwrote:

> This pull request include fix for WF-1589, WF-1582, WF-1581, WF-1583 and
> one warning message fix in ui-fw.
> 
> On Sun, Feb 3, 2013 at 9:13 AM, Veresh Jain notifications@github.comwrote:
> 
> > which other issue is resolved with these commits
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/intalio/tempo/pull/31#issuecomment-13041878>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/intalio/tempo/pull/31#issuecomment-13047020.

## 

Veresh Jain
Director of Support
Intalio, the modern way to build business applications

**Pull request merged**
